### ISSUE TITLE
Class names can be generated with special characters

### ISSUE THREAD

**Issue by k2snowman69** [SimplrJS/css-to-ts#3]
I ran into a bug and tried to fix it but I can't create branches here... and I'm not going to fork this so I'll just explain and paste the code fix here.

Basically if you run the following command:
`css-to-ts --rootDir \"./src\" --outDir \"./src\" --pattern \"**/*.css\" --suffix css --delimitter .`

the input file will be something like `app.css` and the output file will be `app.css.ts` which is very nice. What isn't nice is the contents of the typescript file...

```
export var App.Css = `.ranking-app {
  text-align: center; }
`;
```

which isn't valid typescript (can't create a variable with a special character in the name).

Fix:
In cli-handler.ts use this method instead

```
    private snakeCaseToCamelCase(fileName: string) {
        let regex = /(\w*)(\-*)/g;
        let camelCaseWithSpecialCharacters = fileName.replace(regex, (match: string, word: string, delimitter: string) => {
            return word.charAt(0).toUpperCase() + word.substr(1).toLowerCase();
        });
        return camelCaseWithSpecialCharacters.replace(/[^0-9a-z]/gi, '');
    }
```

**Comment by DovydasNavickas** [comment]
The issue is clear, just not sure why wouldn't you fork it and fix yourself :) The company is on 2 week vacation now, so we'll fix this only towards the end of the month at best. Reviewing a PR takes less time, though. And we'd do that faster.
