### ISSUE TITLE
@types dependencies should be in dev-dependencies

### ISSUE THREAD

**Issue by k2snowman69** [SimplrJS/css-to-ts#4]
Currently in the package.json there are several @types/ dependencies in the `dependencies` section. These should be moved to the `dev-dependencies` section so that they don't get resolved when people install the package via npm.

**Comment by DovydasNavickas** [comment]
We had this discussion about a year ago, but this summarizes everything better:
https://github.com/Microsoft/types-publisher/issues/81#issuecomment-234051338

Tyles have to be in dependencies for libraries. Otherwise, consumers of the library will have to install tyles dependencies manually.
